### ISSUE TITLE
make spectest FAIL

### ISSUE THREAD

**Issue by florian-pe** [Raku/roast#707] opened 2020-12-01 20:10 UTC
I just did all the instructions here (https://rakudo.org/downloads/rakudo/source) to build rakudo from source.
And I also did the test make test and make spectest.
make spectest failed so I thought I'd report.

Here's my log:
I included previous commands, so do grep ^london to hop at the beggining of each one
[newlog3.txt](https://github.com/Raku/roast/files/5625129/newlog3.txt)

**Comment by vrurg** [comment] 2020-12-01 21:19
Because spectest is supposed to test Raku compiler, your report should've been done in rakudo repository. Just a little note.

More substantial is that you really have an issue but not the one you think about; and the failure you have is, unfortunately, expected.

The failure is caused by no IPv6 address on your system. We currently don't have a way to determine if IPv6 is configured on a box or not. So, _t/spec/S32-io/IO-Socket-Async.t_ currently fails if can't bind to `::1`.

Otherwise you have numerous TODOs what tells me that you're using an outdated roast. I.e. it is passing tests which were failing with earlier versions of Rakudo compiler.

Not sure how did it happen. But there is a line in your output following `make spectest` which looks suspicious:

```
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

It's likely to be caused by the directory where you unwrapped the archive is not been a git repository. Not really a big issue, but worth considering.

**Comment by vrurg** [comment] 2020-12-01 21:31
Ok, I never used the binary release and didn't know that spectest is bundled with it an a non-git repository form. So, passing TODOs are a result of slightly outdated roast version. Nothing for you to be worried about.

**Comment by florian-pensec** [comment] 2020-12-03 18:45
Alright I'll close the issue.
But this is weird is that I have an outdated roast because I followed the build instructions directly from:
https://rakudo.org/downloads/rakudo/source
among which :
curl -LJO https://rakudo.org/latest/rakudo/src

**Comment by vrurg** [comment] 2020-12-03 21:22
@florian-pensec it's just a little problem with the release package. I think the next release will not have this problem.

**Comment by flo-pe** [comment] 2020-12-15 01:44
Alright, thank you for respondig @vrurg

**Comment by Altai-man** [comment] 2021-02-21 14:57
Sorry for the late response.

So 2021.02 release is out and I cannot reproduce any issues, so I guess this can be closed. Please re-open if needed.

**Closed by Altai-man** 2021-02-21 14:57 UTC
